version: '3.8'

services:
  app:
    image: postgres:latest
    container_name: spring-boot-app
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/coworking_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: max123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - db

  db:
    image: postgres:17
    container_name: CoworkingSpaceContainer
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: max123
      POSTGRES_DB: coworking_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
